spring.application.name=foodtech_worker
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/foodtech_db
spring.datasource.username=foodtech_user
spring.datasource.password=foodtech_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
